# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import instruction_pb2 as instruction__pb2


class GRPCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInstruction = channel.unary_unary(
                '/instruction.GRPCService/GetInstruction',
                request_serializer=instruction__pb2.InstructionRequest.SerializeToString,
                response_deserializer=instruction__pb2.InstructionResponse.FromString,
                )


class GRPCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInstruction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInstruction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstruction,
                    request_deserializer=instruction__pb2.InstructionRequest.FromString,
                    response_serializer=instruction__pb2.InstructionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'instruction.GRPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GRPCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInstruction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/instruction.GRPCService/GetInstruction',
            instruction__pb2.InstructionRequest.SerializeToString,
            instruction__pb2.InstructionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
